dist: trusty
sudo: false
language: python
python:
 - "2.7"
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
 - pip install --upgrade setuptools
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
before_script:
 - psql -c "CREATE DATABASE citation_capture_pipeline_test;" -U postgres
script:
 - py.test
after_success:
 - coveralls
